export const allIndianBanks = [
    "State Bank of India (SBI)",
    "Punjab National Bank (PNB)",
    "Bank of Baroda (BoB)",
    "Canara Bank",
    "Union Bank of India",
    "Central Bank of India",
    "Indian Bank",
    "Indian Overseas Bank",
    "UCO Bank",
    "Bank of India",
    "IDBI Bank",
    "HDFC Bank",
    "ICICI Bank",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "IndusInd Bank",
    "Yes Bank",
    "Federal Bank",
    "IDFC FIRST Bank",
    "Bandhan Bank",
    "RBL Bank",
    "Citibank",
    "Standard Chartered Bank",
    "HSBC Bank",
    "Deutsche Bank",
    "Barclays Bank",
    "BNP Paribas",
    "Prathama Bank",
    "Punjab Gramin Bank",
    "Andhra Pradesh Grameena Vikas Bank",
    "Saraswat Cooperative Bank",
    "Cosmos Co-operative Bank",
    "Maharashtra Gramin Bank"
]